GITHUB_TOKEN = "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"
GITHUB_REPO = "PetruckLouxie/databmkgjatim"
GITHUB_BRANCH = "main"

ADMIN_USER = "adminbmkg"
ADMIN_PASS = "jatim2025"
